import type { SceneEntry } from "@/scenes/types";

const COMMON_WIDGETS = ["lastFollower", "lastDonation", "lastGift", "raidHost", "importantMessage", "gameInfo", "viewers", "energyTeranga", "goalDonations"];

export const VERTICAL_SCENES: SceneEntry[] = [
  {
    id: "tiktok-gameplay",
    layout: "vertical",
    title: "Gameplay",
    description: "Gameplay plein cadre, sans webcam.",
    webcamSlot: "none",
    ctaZone: true,
    clean: false,
    widgets: COMMON_WIDGETS,
  },
  {
    id: "tiktok-gameplay-webcam",
    layout: "vertical",
    title: "Gameplay + Webcam",
    description: "Gameplay avec webcam en haut ou en fenêtre flottante.",
    webcamSlot: "float",
    ctaZone: true,
    clean: false,
    widgets: [...COMMON_WIDGETS, "goalLikes", "goalGifts"],
  },
  {
    id: "tiktok-facecam",
    layout: "vertical",
    title: "Facecam",
    description: "Webcam en grand format, discussion face caméra.",
    webcamSlot: "full",
    ctaZone: true,
    clean: false,
    widgets: ["lastFollower", "importantMessage", "goalFollowers", "goalDonations"],
  },
  {
    id: "tiktok-justchatting",
    layout: "vertical",
    title: "Just Chatting",
    description: "Discussion, webcam en haut.",
    webcamSlot: "top",
    ctaZone: true,
    clean: false,
    widgets: ["lastFollower", "lastGift", "importantMessage", "gameInfo"],
  },
  {
    id: "tiktok-starting-soon",
    layout: "vertical",
    title: "Starting Soon",
    description: "Écran d'attente vertical.",
    webcamSlot: "none",
    ctaZone: false,
    clean: false,
    widgets: ["timer", "goalFollowers"],
    heroTitle: "ÇA COMMENCE BIENTÔT",
    heroSubtitle: "Dama Ready",
    mascotState: "idle",
  },
  {
    id: "tiktok-pause",
    layout: "vertical",
    title: "Pause",
    description: "Pause courte verticale.",
    webcamSlot: "none",
    ctaZone: false,
    clean: false,
    widgets: ["timer"],
    heroTitle: "PAUSE RAPIDE",
    heroSubtitle: "On revient vite",
    mascotState: "sleep",
  },
  {
    id: "tiktok-ending",
    layout: "vertical",
    title: "Fin de live",
    description: "Écran de fin vertical.",
    webcamSlot: "none",
    ctaZone: false,
    clean: false,
    widgets: [],
    heroTitle: "MERCI {community}",
    heroSubtitle: "À très vite",
    mascotState: "happy",
    showSocials: true,
  },
  {
    id: "tiktok-challenge",
    layout: "vertical",
    title: "Challenge",
    description: "Défi communautaire en cours.",
    webcamSlot: "float",
    ctaZone: true,
    clean: false,
    widgets: [...COMMON_WIDGETS, "goalLikes"],
  },
  {
    id: "tiktok-likes-goal",
    layout: "vertical",
    title: "Objectif likes",
    description: "Focus sur la jauge de likes.",
    webcamSlot: "float",
    ctaZone: true,
    clean: false,
    widgets: ["goalLikes", "lastFollower", "energyTeranga"],
  },
  {
    id: "tiktok-gifts-goal",
    layout: "vertical",
    title: "Objectif cadeaux",
    description: "Focus sur la jauge de cadeaux.",
    webcamSlot: "float",
    ctaZone: true,
    clean: false,
    widgets: ["goalGifts", "lastGift", "energyTeranga"],
  },
  {
    id: "tiktok-battle",
    layout: "vertical",
    title: "Duel / Battle",
    description: "Battle TikTok en tête-à-tête.",
    webcamSlot: "top",
    ctaZone: true,
    clean: false,
    widgets: ["score", "roundsWon", "energyTeranga"],
  },
  {
    id: "tiktok-clip",
    layout: "vertical",
    title: "Clip moment fort",
    description: "Version épurée sans texte pour les moments intenses.",
    webcamSlot: "none",
    ctaZone: false,
    clean: true,
    widgets: [],
  },
];
