import type { SceneEntry } from "@/scenes/types";

const COMMON_WIDGETS = ["lastFollower", "lastSub", "lastGift", "raidHost", "importantMessage", "gameInfo", "viewers", "energyTeranga"];

export const HORIZONTAL_SCENES: SceneEntry[] = [
  {
    id: "twitch-starting-soon",
    layout: "horizontal",
    title: "Starting Soon",
    description: "Écran d'attente avant le direct.",
    webcamSlot: "none",
    ctaZone: false,
    clean: false,
    widgets: ["timer", "goalFollowers", "gameInfo"],
    heroTitle: "EN DIRECT DANS QUELQUES INSTANTS",
    heroSubtitle: "Dama Ready — Nio Far",
    mascotState: "idle",
  },
  {
    id: "twitch-gameplay-webcam",
    layout: "horizontal",
    title: "Gameplay + Webcam",
    description: "Scène principale avec webcam en coin.",
    webcamSlot: "corner",
    ctaZone: false,
    clean: false,
    widgets: [...COMMON_WIDGETS, "score", "terangaRadar", "bossFight"],
  },
  {
    id: "twitch-gameplay-nowebcam",
    layout: "horizontal",
    title: "Gameplay sans webcam",
    description: "Gameplay plein cadre, HUD minimal.",
    webcamSlot: "none",
    ctaZone: false,
    clean: false,
    widgets: [...COMMON_WIDGETS, "score", "terangaRadar", "bossFight"],
  },
  {
    id: "twitch-justchatting",
    layout: "horizontal",
    title: "Just Chatting",
    description: "Discussion, webcam au centre.",
    webcamSlot: "corner",
    ctaZone: false,
    clean: false,
    widgets: COMMON_WIDGETS,
  },
  {
    id: "twitch-brb",
    layout: "horizontal",
    title: "BRB / Pause",
    description: "Pause courte.",
    webcamSlot: "none",
    ctaZone: false,
    clean: false,
    widgets: ["timer", "gameInfo"],
    heroTitle: "DE RETOUR DANS UN INSTANT",
    heroSubtitle: "La mascotte fait une sieste, pas nous",
    mascotState: "sleep",
  },
  {
    id: "twitch-ending",
    layout: "horizontal",
    title: "Fin de stream",
    description: "Écran de fin, remerciements.",
    webcamSlot: "none",
    ctaZone: false,
    clean: false,
    widgets: ["gameInfo"],
    heroTitle: "MERCI FLAA'S SQUAD",
    heroSubtitle: "On se retrouve au prochain live",
    mascotState: "happy",
    showSocials: true,
  },
  {
    id: "twitch-victory",
    layout: "horizontal",
    title: "Victoire",
    description: "Écran de victoire.",
    webcamSlot: "none",
    ctaZone: false,
    clean: false,
    widgets: ["score"],
    heroTitle: "VICTOIRE",
    heroSubtitle: "On est ensemble",
    mascotState: "fire",
    accent: "victory",
  },
  {
    id: "twitch-defeat",
    layout: "horizontal",
    title: "Défaite",
    description: "Défaite honorable.",
    webcamSlot: "none",
    ctaZone: false,
    clean: false,
    widgets: ["score"],
    heroTitle: "DÉFAITE HONORABLE",
    heroSubtitle: "On revient plus fort",
    mascotState: "angry",
    accent: "defeat",
  },
  {
    id: "twitch-tournament",
    layout: "horizontal",
    title: "Tournoi",
    description: "Scène de tournoi/compétition.",
    webcamSlot: "corner",
    ctaZone: false,
    clean: false,
    widgets: [...COMMON_WIDGETS, "score", "roundsWon", "ranking"],
    accent: "tournament",
  },
  {
    id: "twitch-community",
    layout: "horizontal",
    title: "Discussion communauté",
    description: "Mise en avant des réseaux et de la communauté.",
    webcamSlot: "corner",
    ctaZone: false,
    clean: false,
    widgets: ["lastFollower", "lastSub", "importantMessage", "gameInfo"],
    showSocials: true,
  },
  {
    id: "twitch-transition",
    layout: "horizontal",
    title: "Transition de jeu",
    description: "Écran court entre deux jeux.",
    webcamSlot: "none",
    ctaZone: false,
    clean: false,
    widgets: ["gameInfo"],
    heroTitle: "CHANGEMENT DE JEU",
    heroSubtitle: "Une seconde, on recharge l'énergie",
    mascotState: "idle",
  },
];
